name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # 触发条件可以根据需要修改

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境进行构建

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # 获取代码仓库

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets 中存储的 Docker Hub 用户名
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets 中存储的 Docker Hub 密码

    - name: Build Docker Image
      run: docker build -t zhaozuodong/gomitmproxy:latest .

    - name: Push Docker Image
      run: docker push zhaozuodong/gomitmproxy:latest
